### ISSUE TITLE
Default value to be placed in Currently selected box

### ISSUE THREAD

**Issue by vladotesanovic** [truckingsim/Ajax-Bootstrap-Select#121] opened 2017-05-12 10:01 UTC
Hey, 

I'm struggling to achieve this. I want my default value to be placed in Currently selected box.

https://github.com/truckingsim/Ajax-Bootstrap-Select#optionspreserveselected

This is default state when form and default value is loaded:
![Default](http://storage7.static.itmages.com/i/17/0512/h_1494583053_7759124_655a956001.png)

But i want to have it like this ( this is after click event  )
![Default](http://storage2.static.itmages.com/i/17/0512/h_1494583186_6983705_8343278dcd.png)

This is my configuration block ( types are there because i m using TypeScript ):
```javascript
selectObject.ajaxSelectPicker({
        ajax: {
          url: `${config.apiEndpoint}${url}`,
          type: 'GET',
          headers: {
            'Authorization': `Bearer ${localStorage.getItem(config.tokenName)}`
          },
          dataType: 'json',
          data: {
            searchBy: '{{{q}}}',
            maxResults: 5
          }
        },
        emptyRequest: false,
        preprocessData: function (data: Object[]) {

          return data.map((item: any) => {
            return Object.assign({}, {
              'value': item[key],
              'text': item[value],
              'disabled': false
            });
          });
        },
        preserveSelectedPosition: 'before',
        preserveSelected: true
      });
```

**Comment by truckingsim** [comment] 2017-05-12 14:54
@vladotesanovic this has been a bug for a while #41 is basically the same thing.  Thanks for the new use case gives me one more thing to try to narrow it down.  I've tried multiple times to fix this, but we're going to try again for the 2.0.0 rewrite.

**Comment by truckingsim** [comment] 2017-07-21 23:43
duplicate of #41

**Closed** 2017-07-21 23:43 UTC
